name: phyloresistomics_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - iqtree>=2.2.0
  - biopython
  - pandas
  - r-base>=4.2
  - r-tidyverse
  - r-complexheatmap
